# Generated by Django 5.2.8 on 2026-09-27 05:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teachers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentModel',
            fields=[
                ('basicinfomodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='teachers.basicinfomodel')),
                ('roll', models.PositiveIntegerField(null=True)),
                ('image', models.ImageField(upload_to='media/student_img')),
                ('student', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
            bases=('teachers.basicinfomodel',),
        ),
    ]
