# Generated by Django 5.2.8 on 2026-09-30 16:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_coursecategorymodel_id_alter_coursemodel_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursemodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coursemodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
