# Generated by Django 5.2.8 on 2026-10-04 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_coursemodel_created_at_coursemodel_updated_at'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseEnrollmentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adminssion_fee', models.FloatField(null=True)),
                ('pay', models.FloatField(null=True)),
                ('due', models.FloatField(null=True)),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.coursemodel')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_enroll', to='students.studentmodel')),
            ],
        ),
    ]
