# Generated by Django 5.2.8 on 2026-10-04 18:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_courseenrollmentmodel'),
        ('teachers', '0002_alter_basicinfomodel_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherAssignModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.coursemodel')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_teacher', to='teachers.teachermodel')),
            ],
        ),
    ]
