# Generated by Django 5.2.8 on 2026-10-05 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_teacherassignmodel'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseenrollmentmodel',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.coursemodel'),
        ),
        migrations.AlterField(
            model_name='courseenrollmentmodel',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_enroll', to='students.studentmodel'),
        ),
        migrations.AddConstraint(
            model_name='courseenrollmentmodel',
            constraint=models.UniqueConstraint(fields=('student', 'course'), name='unique_student_course'),
        ),
    ]
